// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB84zuX_On4UPzjlQiy8iicYomOysXOLGU',
    appId: '1:637101543789:web:1dadf52ea5d2c735e14a64',
    messagingSenderId: '637101543789',
    projectId: 'buildit-construction-app',
    authDomain: 'buildit-construction-app.firebaseapp.com',
    databaseURL: 'https://buildit-construction-app-default-rtdb.firebaseio.com',
    storageBucket: 'buildit-construction-app.appspot.com',
    measurementId: 'G-WBDVKEQZQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmZrg8OCpkd3BkYdRD-0TRKCZvv94-vT4',
    appId: '1:637101543789:android:8c642f37f47a0846e14a64',
    messagingSenderId: '637101543789',
    projectId: 'buildit-construction-app',
    databaseURL: 'https://buildit-construction-app-default-rtdb.firebaseio.com',
    storageBucket: 'buildit-construction-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBUXFnYsBuWg0_nHCkD10TJSzxglhgvXw',
    appId: '1:637101543789:ios:15a2a289086d0888e14a64',
    messagingSenderId: '637101543789',
    projectId: 'buildit-construction-app',
    databaseURL: 'https://buildit-construction-app-default-rtdb.firebaseio.com',
    storageBucket: 'buildit-construction-app.appspot.com',
    iosClientId: '637101543789-jrf677qkjpv28k3b1374ipum8oqr0c2f.apps.googleusercontent.com',
    iosBundleId: 'com.fyp.buildit',
  );
}
